var classItem__name__string =
[
    [ "Item_name_string", "classItem__name__string.html#a6950cba81c4e7e699dbb90cd75c5240b", null ],
    [ "Item_name_string", "classItem__name__string.html#a90dc22dda61f711fc1a3d4c97f3d6049", null ],
    [ "copy", "classItem__name__string.html#a41f16804fbc5f43c4aa334fe422bdd94", null ],
    [ "is_autogenerated", "classItem__name__string.html#a1b3f79fa7f2163cb8b70fe9af585e7ea", null ],
    [ "set_autogenerated", "classItem__name__string.html#a1adb2066d0911a1470f404f4bfbbc229", null ],
    [ "m_is_autogenerated", "classItem__name__string.html#abfce9f06760ed120d6e093402d4e3863", null ]
];