var dir_70d4c64b7fa4d8934a31e8e779c55748 =
[
    [ "components", "dir_6f7e4693373894924edb8e6e89aa0d51.html", "dir_6f7e4693373894924edb8e6e89aa0d51" ],
    [ "psi", "dir_23167d737535013b9fd584f2b58dba96.html", "dir_23167d737535013b9fd584f2b58dba96" ],
    [ "client_authentication.h", "client__authentication_8h.html", "client__authentication_8h" ],
    [ "client_plugin.h", "client__plugin_8h.html", "client__plugin_8h" ],
    [ "com_data.h", "com__data_8h.html", [
      [ "COM_INIT_DB_DATA", "structCOM__INIT__DB__DATA.html", "structCOM__INIT__DB__DATA" ],
      [ "COM_REFRESH_DATA", "structCOM__REFRESH__DATA.html", "structCOM__REFRESH__DATA" ],
      [ "COM_KILL_DATA", "structCOM__KILL__DATA.html", "structCOM__KILL__DATA" ],
      [ "COM_SET_OPTION_DATA", "structCOM__SET__OPTION__DATA.html", "structCOM__SET__OPTION__DATA" ],
      [ "PS_PARAM", "structPS__PARAM.html", "structPS__PARAM" ],
      [ "COM_STMT_EXECUTE_DATA", "structCOM__STMT__EXECUTE__DATA.html", "structCOM__STMT__EXECUTE__DATA" ],
      [ "COM_STMT_FETCH_DATA", "structCOM__STMT__FETCH__DATA.html", "structCOM__STMT__FETCH__DATA" ],
      [ "COM_STMT_SEND_LONG_DATA_DATA", "structCOM__STMT__SEND__LONG__DATA__DATA.html", "structCOM__STMT__SEND__LONG__DATA__DATA" ],
      [ "COM_STMT_PREPARE_DATA", "structCOM__STMT__PREPARE__DATA.html", "structCOM__STMT__PREPARE__DATA" ],
      [ "COM_STMT_CLOSE_DATA", "structCOM__STMT__CLOSE__DATA.html", "structCOM__STMT__CLOSE__DATA" ],
      [ "COM_STMT_RESET_DATA", "structCOM__STMT__RESET__DATA.html", "structCOM__STMT__RESET__DATA" ],
      [ "COM_QUERY_DATA", "structCOM__QUERY__DATA.html", "structCOM__QUERY__DATA" ],
      [ "COM_FIELD_LIST_DATA", "structCOM__FIELD__LIST__DATA.html", "structCOM__FIELD__LIST__DATA" ],
      [ "COM_DATA", "unionCOM__DATA.html", "unionCOM__DATA" ]
    ] ],
    [ "group_replication_priv.h", "group__replication__priv_8h.html", "group__replication__priv_8h" ],
    [ "innodb_priv.h", "innodb__priv_8h.html", "innodb__priv_8h" ],
    [ "mysql_lex_string.h", "mysql__lex__string_8h.html", [
      [ "MYSQL_LEX_STRING", "structMYSQL__LEX__STRING.html", "structMYSQL__LEX__STRING" ],
      [ "MYSQL_LEX_CSTRING", "structMYSQL__LEX__CSTRING.html", "structMYSQL__LEX__CSTRING" ]
    ] ],
    [ "plugin.h", "include_2mysql_2plugin_8h.html", "include_2mysql_2plugin_8h" ],
    [ "plugin_audit.h", "plugin__audit_8h.html", "plugin__audit_8h" ],
    [ "plugin_audit_message_types.h", "plugin__audit__message__types_8h.html", "plugin__audit__message__types_8h" ],
    [ "plugin_auth.h", "plugin__auth_8h.html", "plugin__auth_8h" ],
    [ "plugin_auth_common.h", "plugin__auth__common_8h.html", "plugin__auth__common_8h" ],
    [ "plugin_clone.h", "plugin__clone_8h.html", "plugin__clone_8h" ],
    [ "plugin_ftparser.h", "plugin__ftparser_8h.html", "plugin__ftparser_8h" ],
    [ "plugin_group_replication.h", "plugin__group__replication_8h.html", "plugin__group__replication_8h" ],
    [ "plugin_keyring.h", "plugin__keyring_8h.html", "plugin__keyring_8h" ],
    [ "plugin_query_rewrite.h", "plugin__query__rewrite_8h.html", "plugin__query__rewrite_8h" ],
    [ "plugin_trace.h", "plugin__trace_8h.html", "plugin__trace_8h" ],
    [ "plugin_validate_password.h", "plugin__validate__password_8h.html", "plugin__validate__password_8h" ],
    [ "service_command.h", "service__command_8h.html", "service__command_8h" ],
    [ "service_locking.h", "service__locking_8h.html", "service__locking_8h" ],
    [ "service_my_plugin_log.h", "service__my__plugin__log_8h.html", "service__my__plugin__log_8h" ],
    [ "service_mysql_alloc.h", "service__mysql__alloc_8h.html", "service__mysql__alloc_8h" ],
    [ "service_mysql_keyring.h", "service__mysql__keyring_8h.html", "service__mysql__keyring_8h" ],
    [ "service_mysql_password_policy.h", "service__mysql__password__policy_8h.html", "service__mysql__password__policy_8h" ],
    [ "service_mysql_string.h", "service__mysql__string_8h.html", "service__mysql__string_8h" ],
    [ "service_parser.h", "service__parser_8h.html", "service__parser_8h" ],
    [ "service_plugin_registry.h", "service__plugin__registry_8h.html", "service__plugin__registry_8h" ],
    [ "service_rpl_transaction_ctx.h", "service__rpl__transaction__ctx_8h.html", "service__rpl__transaction__ctx_8h" ],
    [ "service_rpl_transaction_write_set.h", "service__rpl__transaction__write__set_8h.html", "service__rpl__transaction__write__set_8h" ],
    [ "service_rules_table.h", "service__rules__table_8h.html", "service__rules__table_8h" ],
    [ "service_security_context.h", "service__security__context_8h.html", "service__security__context_8h" ],
    [ "service_srv_session.h", "service__srv__session_8h.html", "service__srv__session_8h" ],
    [ "service_srv_session_bits.h", "service__srv__session__bits_8h.html", "service__srv__session__bits_8h" ],
    [ "service_srv_session_info.h", "service__srv__session__info_8h.html", "service__srv__session__info_8h" ],
    [ "service_ssl_wrapper.h", "service__ssl__wrapper_8h.html", "service__ssl__wrapper_8h" ],
    [ "service_thd_alloc.h", "service__thd__alloc_8h.html", "service__thd__alloc_8h" ],
    [ "service_thd_engine_lock.h", "service__thd__engine__lock_8h.html", "service__thd__engine__lock_8h" ],
    [ "service_thd_wait.h", "service__thd__wait_8h.html", "service__thd__wait_8h" ],
    [ "service_thread_scheduler.h", "service__thread__scheduler_8h.html", "service__thread__scheduler_8h" ],
    [ "services.h", "include_2mysql_2services_8h.html", "include_2mysql_2services_8h" ],
    [ "status_var.h", "status__var_8h.html", "status__var_8h" ],
    [ "thread_pool_priv.h", "thread__pool__priv_8h.html", "thread__pool__priv_8h" ],
    [ "thread_type.h", "thread__type_8h.html", "thread__type_8h" ],
    [ "udf_registration_types.h", "udf__registration__types_8h.html", "udf__registration__types_8h" ]
];