var namespacedd_1_1tables =
[
    [ "Catalogs", "classdd_1_1tables_1_1Catalogs.html", "classdd_1_1tables_1_1Catalogs" ],
    [ "Character_sets", "classdd_1_1tables_1_1Character__sets.html", "classdd_1_1tables_1_1Character__sets" ],
    [ "Check_constraints", "classdd_1_1tables_1_1Check__constraints.html", "classdd_1_1tables_1_1Check__constraints" ],
    [ "Collations", "classdd_1_1tables_1_1Collations.html", "classdd_1_1tables_1_1Collations" ],
    [ "Column_statistics", "classdd_1_1tables_1_1Column__statistics.html", "classdd_1_1tables_1_1Column__statistics" ],
    [ "Column_type_elements", "classdd_1_1tables_1_1Column__type__elements.html", "classdd_1_1tables_1_1Column__type__elements" ],
    [ "Columns", "classdd_1_1tables_1_1Columns.html", "classdd_1_1tables_1_1Columns" ],
    [ "DD_properties", "classdd_1_1tables_1_1DD__properties.html", "classdd_1_1tables_1_1DD__properties" ],
    [ "Events", "classdd_1_1tables_1_1Events.html", "classdd_1_1tables_1_1Events" ],
    [ "Foreign_key_column_usage", "classdd_1_1tables_1_1Foreign__key__column__usage.html", "classdd_1_1tables_1_1Foreign__key__column__usage" ],
    [ "Foreign_keys", "classdd_1_1tables_1_1Foreign__keys.html", "classdd_1_1tables_1_1Foreign__keys" ],
    [ "Index_column_usage", "classdd_1_1tables_1_1Index__column__usage.html", "classdd_1_1tables_1_1Index__column__usage" ],
    [ "Index_partitions", "classdd_1_1tables_1_1Index__partitions.html", "classdd_1_1tables_1_1Index__partitions" ],
    [ "Index_stats", "classdd_1_1tables_1_1Index__stats.html", "classdd_1_1tables_1_1Index__stats" ],
    [ "Indexes", "classdd_1_1tables_1_1Indexes.html", "classdd_1_1tables_1_1Indexes" ],
    [ "Parameter_type_elements", "classdd_1_1tables_1_1Parameter__type__elements.html", "classdd_1_1tables_1_1Parameter__type__elements" ],
    [ "Parameters", "classdd_1_1tables_1_1Parameters.html", "classdd_1_1tables_1_1Parameters" ],
    [ "Resource_groups", "classdd_1_1tables_1_1Resource__groups.html", "classdd_1_1tables_1_1Resource__groups" ],
    [ "Routines", "classdd_1_1tables_1_1Routines.html", "classdd_1_1tables_1_1Routines" ],
    [ "Schemata", "classdd_1_1tables_1_1Schemata.html", "classdd_1_1tables_1_1Schemata" ],
    [ "Spatial_reference_systems", "classdd_1_1tables_1_1Spatial__reference__systems.html", "classdd_1_1tables_1_1Spatial__reference__systems" ],
    [ "Table_partition_values", "classdd_1_1tables_1_1Table__partition__values.html", "classdd_1_1tables_1_1Table__partition__values" ],
    [ "Table_partition_values_pk", "classdd_1_1tables_1_1Table__partition__values__pk.html", "classdd_1_1tables_1_1Table__partition__values__pk" ],
    [ "Table_partitions", "classdd_1_1tables_1_1Table__partitions.html", "classdd_1_1tables_1_1Table__partitions" ],
    [ "Table_stats", "classdd_1_1tables_1_1Table__stats.html", "classdd_1_1tables_1_1Table__stats" ],
    [ "Tables", "classdd_1_1tables_1_1Tables.html", "classdd_1_1tables_1_1Tables" ],
    [ "Tablespace_files", "classdd_1_1tables_1_1Tablespace__files.html", "classdd_1_1tables_1_1Tablespace__files" ],
    [ "Tablespaces", "classdd_1_1tables_1_1Tablespaces.html", "classdd_1_1tables_1_1Tablespaces" ],
    [ "Triggers", "classdd_1_1tables_1_1Triggers.html", "classdd_1_1tables_1_1Triggers" ],
    [ "View_routine_usage", "classdd_1_1tables_1_1View__routine__usage.html", "classdd_1_1tables_1_1View__routine__usage" ],
    [ "View_table_usage", "classdd_1_1tables_1_1View__table__usage.html", "classdd_1_1tables_1_1View__table__usage" ]
];