var opt__range_8h =
[
    [ "KEY_PART", "structKEY__PART.html", "structKEY__PART" ],
    [ "QUICK_RANGE", "classQUICK__RANGE.html", "classQUICK__RANGE" ],
    [ "QUICK_SELECT_I", "classQUICK__SELECT__I.html", "classQUICK__SELECT__I" ],
    [ "QUICK_RANGE_SEQ_CTX", "structQUICK__RANGE__SEQ__CTX.html", "structQUICK__RANGE__SEQ__CTX" ],
    [ "QUICK_RANGE_SELECT", "classQUICK__RANGE__SELECT.html", "classQUICK__RANGE__SELECT" ],
    [ "QUICK_RANGE_SELECT_GEOM", "classQUICK__RANGE__SELECT__GEOM.html", "classQUICK__RANGE__SELECT__GEOM" ],
    [ "QUICK_INDEX_MERGE_SELECT", "classQUICK__INDEX__MERGE__SELECT.html", "classQUICK__INDEX__MERGE__SELECT" ],
    [ "QUICK_ROR_INTERSECT_SELECT", "classQUICK__ROR__INTERSECT__SELECT.html", "classQUICK__ROR__INTERSECT__SELECT" ],
    [ "Quick_ror_union_less", "structQuick__ror__union__less.html", "structQuick__ror__union__less" ],
    [ "QUICK_ROR_UNION_SELECT", "classQUICK__ROR__UNION__SELECT.html", "classQUICK__ROR__UNION__SELECT" ],
    [ "QUICK_GROUP_MIN_MAX_SELECT", "classQUICK__GROUP__MIN__MAX__SELECT.html", "classQUICK__GROUP__MIN__MAX__SELECT" ],
    [ "QUICK_SELECT_DESC", "classQUICK__SELECT__DESC.html", "classQUICK__SELECT__DESC" ],
    [ "QUICK_SKIP_SCAN_SELECT", "classQUICK__SKIP__SCAN__SELECT.html", "classQUICK__SKIP__SCAN__SELECT" ],
    [ "Quick_ranges", "opt__range_8h.html#a3f8a19f08f3959d914d8e2383ea490d4", null ],
    [ "Quick_ranges_array", "opt__range_8h.html#a65fb3b574365ef995bc34f220ae77f70", null ],
    [ "prune_partitions", "opt__range_8h.html#acb637143f6e8ecfd3980c474ed0a19e9", null ],
    [ "quick_range_seq_init", "opt__range_8h.html#ac37903eb4cf07a4ec47ba77060d39579", null ],
    [ "quick_range_seq_next", "opt__range_8h.html#a0e69f3a3005d77d7e779e5326e56ec26", null ],
    [ "range_optimizer_free", "opt__range_8h.html#aad63b16fee3e1922af5fac2f2bd772cc", null ],
    [ "range_optimizer_init", "opt__range_8h.html#aeb7a6e279a9ab1ac304d1d45395defae", null ],
    [ "store_key_image_to_rec", "opt__range_8h.html#a532bf40caeeb95011cab7d39764af9dd", null ],
    [ "test_quick_select", "opt__range_8h.html#a7d4a3db44a2ad833e69389ad59d74ce4", null ],
    [ "null_string", "opt__range_8h.html#a1afee0a72cd47f67bd0d776d99296a8e", null ]
];